apiVersion: v2
name: jobnik-manager-test
description: A Helm chart for jobnik-manager service
type: application
version: 0.1.9-rc.4
appVersion: 0.1.9-rc.4
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
