apiVersion: v2
name: jobnik-manager
description: A Helm chart for jobnik-manager service
type: application
version: v0.1.1-rc.0
appVersion: v0.1.1-rc.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
